---
name: Bookworm Images
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths: ['bookworm/Dockerfile', 'box64.sh']
  #schedule:
  #  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  release:
    name: Release - Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: current-date
        run: |
          echo "TODAY=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=debian
            type=raw,value=debian-bookworm
          flavor: latest=true

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: bookworm/Dockerfile
          target: bookworm
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max